id = "react-type-kit-snippets"
name = "ReactTypeKit Snippets"
version = "2.0.0"
schema_version = 1
authors = ["Miguel Machado"]
description =  "A comprehensive set of React, React Native, Redux + TypeScript snippets designed to boost productivity and ensure consistent, type-safe code."
repository = "https://github.com/MiguelMachado-dev/ReactTypeKit"
snippets = "./snippets/tsx.json"
